export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_EMPTY = 'CART_EMPTY';
export const CART_SAVE_PRESTATION = 'CART_SAVE_PRESTATION';
export const CART_SAVE_SOUS_PRESTATION = 'CART_SAVE_SOUS_PRESTATION';
export const CART_SAVE_DATE = 'CART_SAVE_DATE';

