export const DEVIS_CREATE_REQUEST = 'DEVIS_CREATE_REQUEST';
export const DEVIS_CREATE_SUCCESS = 'DEVIS_CREATE_SUCCESS';
export const DEVIS_CREATE_FAIL = 'DEVIS_CREATE_FAIL';
export const DEVIS_CREATE_RESET = 'DEVIS_CREATE_RESET';
export const DEVIS_SAVE_NEED_QUOTE = 'DEVIS_SAVE_NEED_QUOTE';
export const DEVIS_SAVE_DATE = 'DEVIS_SAVE_DATE';

export const DEVIS_PAY_REQUEST = 'DEVIS_PAY_REQUEST';
export const DEVIS_PAY_SUCCESS = 'DEVIS_PAY_SUCCESS';
export const DEVIS_PAY_FAIL = 'DEVIS_PAY_FAIL';
export const DEVIS_PAY_RESET = 'DEVIS_PAY_RESET';

export const DEVIS_DELIVER_REQUEST = 'DEVIS_DELIVER_REQUEST';
export const DEVIS_DELIVER_SUCCESS = 'DEVIS_DELIVER_SUCCESS';
export const DEVIS_DELIVER_FAIL = 'DEVIS_DELIVER_FAIL';
export const DEVIS_DELIVER_RESET = 'DEVIS_DELIVER_RESET';

export const DEVIS_DETAILS_REQUEST = 'DEVIS_DETAILS_REQUEST';
export const DEVIS_DETAILS_SUCCESS = 'DEVIS_DETAILS_SUCCESS';
export const DEVIS_DETAILS_FAIL = 'DEVIS_DETAILS_FAIL';

export const DEVIS_MINE_LIST_REQUEST = 'DEVIS_MINE_LIST_REQUEST';
export const DEVIS_MINE_LIST_SUCCESS = 'DEVIS_MINE_LIST_SUCCESS';
export const DEVIS_MINE_LIST_FAIL = 'DEVIS_MINE_LIST_FAIL';

export const DEVIS_LIST_REQUEST = 'DEVIS_LIST_REQUEST';
export const DEVIS_LIST_SUCCESS = 'DEVIS_LIST_SUCCESS';
export const DEVIS_LIST_FAIL = 'DEVIS_LIST_FAIL';

export const DEVIS_DELETE_REQUEST = 'DEVIS_DELETE_REQUEST';
export const DEVIS_DELETE_SUCCESS = 'DEVIS_DELETE_SUCCESS';
export const DEVIS_DELETE_FAIL = 'DEVIS_DELETE_FAIL';
export const DEVIS_DELETE_RESET = 'DEVIS_DELETE_RESET';

export const DEVIS_SUMMARY_REQUEST = 'DEVIS_SUMMARY_REQUEST';
export const DEVIS_SUMMARY_SUCCESS = 'DEVIS_SUMMARY_SUCCESS';
export const DEVIS_SUMMARY_FAIL = 'DEVIS_SUMMARY_FAIL';
