export const PRESTATION_LIST_REQUEST = 'PRESTATION_LIST_REQUEST';
export const PRESTATION_LIST_SUCCESS = 'PRESTATION_LIST_SUCCESS';
export const PRESTATION_LIST_FAIL = 'PRESTATION_LIST_FAIL';

export const PRESTATION_DETAILS_REQUEST = 'PRESTATION_DETAILS_REQUEST';
export const PRESTATION_DETAILS_SUCCESS = 'PRESTATION_DETAILS_SUCCESS';
export const PRESTATION_DETAILS_FAIL = 'PRESTATION_DETAILS_FAIL';

export const PRESTATION_CREATE_REQUEST = 'PRESTATION_CREATE_REQUEST';
export const PRESTATION_CREATE_SUCCESS = 'PRESTATION_CREATE_SUCCESS';
export const PRESTATION_CREATE_FAIL = 'PRESTATION_CREATE_FAIL';
export const PRESTATION_CREATE_RESET = 'PRESTATION_CREATE_RESET';

export const PRESTATION_TYPE_CREATE_REQUEST = 'PRESTATION_TYPE_CREATE_REQUEST';
export const PRESTATION_TYPE_CREATE_SUCCESS = 'PRESTATION_TYPE_CREATE_SUCCESS';
export const PRESTATION_TYPE_CREATE_FAIL = 'PRESTATION_TYPE_CREATE_FAIL';
export const PRESTATION_TYPE_CREATE_RESET = 'PRESTATION_TYPE_CREATE_RESET';

export const PRESTATION_UPDATE_REQUEST = 'PRESTATION_UPDATE_REQUEST';
export const PRESTATION_UPDATE_SUCCESS = 'PRESTATION_UPDATE_SUCCESS';
export const PRESTATION_UPDATE_FAIL = 'PRESTATION_UPDATE_FAIL';
export const PRESTATION_UPDATE_RESET = 'PRESTATION_UPDATE_RESET';

export const PRESTATION_DELETE_REQUEST = 'PRESTATION_DELETE_REQUEST';
export const PRESTATION_DELETE_SUCCESS = 'PRESTATION_DELETE_SUCCESS';
export const PRESTATION_DELETE_FAIL = 'PRESTATION_DELETE_FAIL';
export const PRESTATION_DELETE_RESET = 'PRESTATION_DELETE_RESET';

export const PRESTATION_CATEGORY_LIST_REQUEST = 'PRESTATION_CATEGORY_LIST_REQUEST';
export const PRESTATION_CATEGORY_LIST_SUCCESS = 'PRESTATION_CATEGORY_LIST_SUCCESS';
export const PRESTATION_CATEGORY_LIST_FAIL = 'PRESTATION_CATEGORY_LIST_FAIL';
